version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: taskflow-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - taskflow-net

  backend:
    build: ./backend
    container_name: taskflow-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/taskflow
    depends_on:
      - mongo
    networks:
      - taskflow-net

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:5000/api/tasks
    container_name: taskflow-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - taskflow-net

volumes:
  mongo-data:

networks:
  taskflow-net: